### ISSUE TITLE
SQL SERVER 2014

### ISSUE THREAD

**Issue by YenaroOsorio** [carlosriosacevedo17/basesdedatosprim2020#1]
perdon por la pregunta profesor pero que opcion le tenemos que poner manual??
Le envio una imagen con las opciones 
![imagen](https://user-images.githubusercontent.com/58090359/74986366-f70f6000-53fe-11ea-9cb5-a6bf617116fc.png)

https://user-images.githubusercontent.com/58090359/74986366-f70f6000-53fe-11ea-9cb5-a6bf617116fc.png

GRACIAS...

**Comment by carlosriosacevedo17** [comment]
manual en sql server browser. Saludos
